<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>RepoLiveControlV8</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RepoGamePath Condition="'$(RepoGamePath)' == ''">C:\Program Files (x86)\Steam\steamapps\common\REPO</RepoGamePath>
    <RepoProfilePath Condition="'$(RepoProfilePath)' == ''">C:\Users\James Kieley\AppData\Roaming\Thunderstore Mod Manager\DataFolder\REPO\profiles\modded</RepoProfilePath>
    <ManagedPath>$(RepoGamePath)\REPO_Data\Managed</ManagedPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="RepoLiveControl.cs" />
    <Reference Include="0Harmony" HintPath="$(RepoProfilePath)\BepInEx\core\0Harmony.dll" />
    <Reference Include="BepInEx" HintPath="$(RepoProfilePath)\BepInEx\core\BepInEx.dll" />
    <Reference Include="REPOLib" HintPath="$(RepoProfilePath)\BepInEx\plugins\Zehs-REPOLib\REPOLib.dll" />
    <Reference Include="Assembly-CSharp" HintPath="$(ManagedPath)\Assembly-CSharp.dll" />
    <Reference Include="UnityEngine" HintPath="$(ManagedPath)\UnityEngine.dll" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(ManagedPath)\UnityEngine.CoreModule.dll" />
    <Reference Include="UnityEngine.PhysicsModule" HintPath="$(ManagedPath)\UnityEngine.PhysicsModule.dll" />
    <Reference Include="PhotonUnityNetworking" HintPath="$(ManagedPath)\PhotonUnityNetworking.dll" />
    <Reference Include="PhotonRealtime" HintPath="$(ManagedPath)\PhotonRealtime.dll" />
  </ItemGroup>
</Project>
